#! /bin/bash

echo "====================================================================================="
echo ""
echo "HEAP_PROFILE_ALLOCATION_INTERVAL      = ${HEAP_PROFILE_ALLOCATION_INTERVAL}"
echo "HEAP_PROFILE_INUSE_INTERVAL           = ${HEAP_PROFILE_INUSE_INTERVAL}"
echo "HEAP_PROFILE_TIME_INTERVAL            = ${HEAP_PROFILE_TIME_INTERVAL}"
echo "HEAPPROFILESIGNAL                     = ${HEAPPROFILESIGNAL}"
echo "HEAP_PROFILE_MMAP                     = ${HEAP_PROFILE_MMAP}"
echo "HEAP_PROFILE_ONLY_MMAP                = ${HEAP_PROFILE_ONLY_MMAP}"
echo "HEAP_PROFILE_MMAP_LOG                 = ${HEAP_PROFILE_MMAP_LOG}"
echo "====================================================================================="
echo ""
echo "TCMALLOC_SAMPLE_PARAMETER             = ${TCMALLOC_SAMPLE_PARAMETER}"
echo "TCMALLOC_RELEASE_RATE                 = ${TCMALLOC_RELEASE_RATE}"
echo "TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD = ${TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD}"
echo "TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES = ${TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES}"
echo "====================================================================================="
echo ""